# Generated by Django 4.2.13 on 2024-06-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('duracion', models.IntegerField()),
                ('capacidad', models.IntegerField()),
            ],
        ),
    ]
